classdef Tutorial_2_Objective_AD < Dynamic_Objective_AD
    % Objective function for an orbital dynamics problem.
    %
    % min \int_{0}^{T} ||y - (r, 0, wt, t)^T)||^2 dt
    %
    % Here y = (r, r', w, w') represents radius, change in radius, angular
    % momentum, and change in angular momentum of an object. The constants
    % r and w are the target radius and angular momentum.

    properties
        radius       % Target orbital radius.
        velocity     % Target angular velocity.
    end

    methods

        function this = Tutorial_2_Objective_AD(T, n_t, radius, velocity)
            this = this@Dynamic_Objective_AD(4, 2, T, n_t);
            this.radius = radius;
            this.velocity = velocity;
        end

        function [val] = g_AD(this, y, t)
            w = this.velocity;
            val = sum((y - [this.radius; 0; w * t; w]).^2);
        end

        function [val] = R_AD(this, z)
            val = sum((z - [this.radius; this.velocity]).^2);
            % val = 0;  % BUG: no derivatives of R are autogenerated.
        end

        function Plot(this, u)
            % Plot a trajectory two ways: x(t) and y(t) in time, and
            % (x(t),y(t)) as a 2D trajectory.
            %
            % Parameters
            % ----------
            % u
            %   Solution array, either an :math:`n_y \times n_t` matrix or
            %   an :math:`(n_y n_t, 1)` vector.

            t = this.t_mesh;
            x_goal = this.radius * cos(this.velocity .* t);
            y_goal = this.radius * sin(this.velocity .* t);

            ys = reshape(u, this.n_y, this.n_t);
            r = ys(1, :);
            theta = ys(3, :);
            x = r .* cos(theta);
            y = r .* sin(theta);
            lim = 1.1 * max(r);

            fig = figure;
            fig.Position(3:4) = [840 420];
            subplot(1, 2, 1);
            plot(t, x, '-', 'DisplayName', 'x(t)');
            hold on;
            plot(t, y, '--', 'DisplayName', 'y(t)');
            xlim([0, t(end)]);
            ylim([-lim, lim]);
            xlabel('t');
            title('x and y coordinates over time');
            legend;

            subplot(1, 2, 2);
            plot(x_goal, y_goal, 'k--', 'LineWidth', 2, 'DisplayName', 'target trajectory');
            hold on;
            plot(x, y, '-', 'DisplayName', 'realized trajectory');
            plot(x(1), y(1), '.', 'MarkerSize', 16, 'DisplayName', 'initial position');
            xlim([-lim, lim]);
            ylim([-lim, lim]);
            xlabel('x(t)');
            ylabel('y(t)');
            title('position');
            axis('equal');
            legend;
        end

    end
end
