classdef Tutorial_2_Objective_AD < Dynamic_Objective_AD
    % Objective function for an orbital dynamics problem.
    %
    % min \int_{0}^{T} ||y - (r, 0, wt, t)^T)||^2 dt
    %
    % Here y = (r, r', w, w') represents radius, change in radius, angular
    % momentum, and change in angular momentum of an object. The constants
    % r and w are the target radius and angular momentum.

    properties
        radius       % Target orbital radius.
        velocity     % Target angular velocity.
    end

    methods

        function this = Tutorial_2_Objective_AD(n_y, n_z, T, n_t, radius, velocity)
            this = this@Dynamic_Objective_AD(n_y, n_z, T, n_t);
            this.radius = radius;
            this.velocity = velocity;
        end

        function [val] = g_AD(this, y, t)
            w = this.velocity;
            val = sum((y - [this.radius; 0; w * t; w]).^2);
        end

        function [val] = R_AD(this, z)
            val = sum((z - [this.radius; this.velocity]).^2);
            % val = 0;  % BUG: no derivatives of R are autogenerated.
        end

    end
end
