%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%      Sola - Sandbox for Outer Loop Analysis         %%%%%%%%%
%%%%%%%%% Questions? Contact Joseph Hart (joshart@sandia.gov) %%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

currpath = pwd();

% This line sets the sola/src/ code path
addpath(genpath([currpath, '/src/']));

% This line adds sola/src to the Matlab default paths
savepath;

fprintf([ ...
         '     \n', ...
         '     Sola - Sandbox for Outer Loop Analysis \n', ...
         '     Questions? Contact Joseph Hart (joshart@sandia.gov) \n', ...
         '     \n', ...
         '     The automatic_differentiation module in Sola requires ADiGator. \n', ...
         '     Please visit https://github.com/matt-weinstein/adigator to download it. \n', ...
         '     This can be omitted. The only source code that depends on ADiGator  \n', ...
         '     is in sola/src/automatic_differentiation. \n', ...
         '     \n', ...
         '     The python_adapter module in Sola requires compatible versions of Matlab and Python. \n', ...
         '     See https://www.mathworks.com/support/requirements/python-compatibility.html for details. \n', ...
         '     This can be omitted. The only source code that depends on Python  \n', ...
         '     is in sola/src/python_adapter. \n', ...
         '     Also, note that the python_adapter may not be updated to support every \n', ...
         '     functionality in Sola. Additional python interfaces can be implemented \n', ...
         '     following the design of the code in sola/src/python_adapter. \n']);
